import type { Shelter } from "./types/shelter";

export const MOCK_SHELTERS: Shelter[] = [
  {
    id: 1,
    name: "Refugio Patitas Felices",
    description:
      "Refugio dedicado al rescate y adopción de perros y gatos abandonados.",
    address: "Av. Corrientes 1234",
    city: "Buenos Aires",
    country: "Argentina",
    phone: "+54 11 1234-5678",
    email: "contacto@patitasfelices.org",
    website: "https://patitasfelices.org",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=PF",
    petCount: 45,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 2,
    name: "Hogar San Roque",
    description: "Protectora de animales desde 1995, especializada en perros.",
    address: "Calle 7 No. 456",
    city: "La Plata",
    country: "Argentina",
    phone: "+54 221 456-7890",
    email: "info@hogarsanroque.org",
    website: "https://hogarsanroque.org",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=HSR",
    petCount: 78,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 3,
    name: "Amigos de 4 Patas",
    description: "Organización sin fines de lucro para el bienestar animal.",
    address: "Bv. San Juan 789",
    city: "Córdoba",
    country: "Argentina",
    phone: "+54 351 987-6543",
    email: "amigos4patas@gmail.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=A4P",
    petCount: 32,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 4,
    name: "Refugio Esperanza",
    description: "Centro de rescate y rehabilitación de animales callejeros.",
    address: "Av. Libertador 2345",
    city: "Rosario",
    country: "Argentina",
    phone: "+54 341 234-5678",
    email: "esperanza@refugio.org",
    website: "https://refugioesperanza.org",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=RE",
    petCount: 56,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 5,
    name: "Gaticos y Perritos",
    description:
      "Refugio familiar dedicado a gatos y perros de todas las edades.",
    address: "Calle Mendoza 567",
    city: "Mendoza",
    country: "Argentina",
    phone: "+54 261 345-6789",
    email: "hola@gaticosyperritos.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=GP",
    petCount: 23,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
