import type { Pet } from "@/features/pets/types/pet";
import { PET_SPECIES, PET_STATUS } from "@/features/pets/constants";

export type ShelterPet = Pet & { shelterId: number };

export const MOCK_SHELTER_PETS: ShelterPet[] = [
  // Shelter 1 - Refugio Patitas Felices
  {
    id: 101,
    shelterId: 1,
    photoUrl: "https://placedog.net/200/200",
    name: "Toto",
    species: PET_SPECIES.DOG,
    breed: "Mestizo",
    status: PET_STATUS.IN_SHELTER,
    age: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 102,
    shelterId: 1,
    photoUrl: "https://cataas.com/cat",
    name: "Michi",
    species: PET_SPECIES.CAT,
    breed: "Común europeo",
    status: PET_STATUS.IN_SHELTER,
    age: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 103,
    shelterId: 1,
    photoUrl: "https://placedog.net/201/201",
    name: "Bruno",
    species: PET_SPECIES.DOG,
    breed: "Labrador",
    status: PET_STATUS.IN_TRANSIT,
    age: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 104,
    shelterId: 1,
    photoUrl: "https://cataas.com/cat/orange",
    name: "Naranja",
    species: PET_SPECIES.CAT,
    breed: "Mestizo",
    status: PET_STATUS.ADOPTED, // Should not appear
    age: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  // Shelter 2 - Hogar San Roque
  {
    id: 201,
    shelterId: 2,
    photoUrl: "https://placedog.net/202/202",
    name: "Rex",
    species: PET_SPECIES.DOG,
    breed: "Pastor Alemán",
    status: PET_STATUS.IN_SHELTER,
    age: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 202,
    shelterId: 2,
    photoUrl: "https://placedog.net/203/203",
    name: "Luna",
    species: PET_SPECIES.DOG,
    breed: "Golden Retriever",
    status: PET_STATUS.IN_SHELTER,
    age: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 203,
    shelterId: 2,
    photoUrl: "https://placedog.net/204/204",
    name: "Canela",
    species: PET_SPECIES.DOG,
    breed: "Cocker Spaniel",
    status: PET_STATUS.IN_VET,
    age: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  // Shelter 3 - Amigos de 4 Patas
  {
    id: 301,
    shelterId: 3,
    photoUrl: "https://cataas.com/cat/cute",
    name: "Pelusa",
    species: PET_SPECIES.CAT,
    breed: "Persa",
    status: PET_STATUS.IN_SHELTER,
    age: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 302,
    shelterId: 3,
    photoUrl: "https://placedog.net/205/205",
    name: "Rocky",
    species: PET_SPECIES.DOG,
    breed: "Pitbull",
    status: PET_STATUS.IN_SHELTER,
    age: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  // Shelter 4 - Refugio Esperanza
  {
    id: 401,
    shelterId: 4,
    photoUrl: "https://placedog.net/206/206",
    name: "Simba",
    species: PET_SPECIES.DOG,
    breed: "Mestizo",
    status: PET_STATUS.IN_SHELTER,
    age: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 402,
    shelterId: 4,
    photoUrl: "https://cataas.com/cat/says/meow",
    name: "Bigotes",
    species: PET_SPECIES.CAT,
    breed: "Siamés",
    status: PET_STATUS.IN_TRANSIT,
    age: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 403,
    shelterId: 4,
    photoUrl: "https://placedog.net/207/207",
    name: "Toby",
    species: PET_SPECIES.DOG,
    breed: "Beagle",
    status: PET_STATUS.IN_SHELTER,
    age: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  // Shelter 5 - Gaticos y Perritos
  {
    id: 501,
    shelterId: 5,
    photoUrl: "https://cataas.com/cat/gif",
    name: "Copito",
    species: PET_SPECIES.CAT,
    breed: "Angora",
    status: PET_STATUS.IN_SHELTER,
    age: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
  {
    id: 502,
    shelterId: 5,
    photoUrl: "https://placedog.net/208/208",
    name: "Coco",
    species: PET_SPECIES.DOG,
    breed: "Poodle",
    status: PET_STATUS.IN_SHELTER,
    age: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    archivedAt: null,
  },
];
